import { Platform, StyleSheet } from "react-native";

/**
 * Shared design tokens and stylesheet for the employee app.
 * Kept in one module so every screen inherits the same surfaces, spacing and
 * type scale — restyling here restyles the whole app.
 */
export const theme = {
  // Canvas and surfaces
  background: "#F1F4F8",
  inset: "#FFFFFF",
  subtle: "#F8FAFC",
  hover: "#F1F5F9",
  shadow: "#CFD7E3",

  // Brand
  primary: "#0F6CBD",
  primaryDark: "#0F6CBD",
  primaryDeep: "#0D4D85",
  primarySoft: "#EFF6FC",
  primaryBorder: "#C7E0F4",

  // Navigation rail, matching the admin console
  navy: "#111827",
  navySoft: "#1A2231",
  navyLine: "#232D3D",
  navyText: "#A9B4C3",
  navyMuted: "#6F7D8F",
  navyAccent: "#55A6EA",

  // Text
  text: "#131A26",
  muted: "#5A6675",
  faint: "#8593A4",

  // Lines
  line: "#E3E8EF",
  lineStrong: "#CFD7E3",
  lineInput: "#B8C2CE",

  // Semantic
  success: "#107C41",
  successSoft: "#EDF7F0",
  warning: "#9A6700",
  warningSoft: "#FFF8E6",
  danger: "#C4314B",
  dangerSoft: "#FDF3F4",
};

export const appFontFamily = Platform.select({
  web: '"Segoe UI Variable Text", "Segoe UI", Arial, sans-serif',
  ios: "System",
  android: "sans-serif",
  default: "System",
});

/** Flat surface: white fill with a hairline border, no drop shadow. */
export const raisedSurface = {
  backgroundColor: theme.inset,
  borderWidth: 1,
  borderColor: theme.line,
};

export const spacing = { xs: 4, sm: 8, md: 12, lg: 16, xl: 20, xxl: 28 };

const TAB_BAR_HEIGHT = Platform.OS === "ios" ? 78 : 64;

export const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: theme.background },

  /* ----------------------------- login ----------------------------- */
  loginScreen: { flex: 1, backgroundColor: theme.navy },
  loginWrap: {
    flex: 1,
    justifyContent: "center",
    padding: 20,
    width: "100%",
    maxWidth: 520,
    alignSelf: "center",
  },
  loginCard: {
    backgroundColor: theme.inset,
    borderRadius: 12,
    padding: 20,
  },
  loginFooter: {
    color: theme.navyMuted,
    textAlign: "center",
    marginTop: 18,
    fontSize: 12,
    lineHeight: 18,
  },
  brand: { flexDirection: "row", alignItems: "center", gap: 12, marginBottom: 22 },
  logo: {
    width: 44,
    height: 44,
    textAlign: "center",
    paddingTop: Platform.OS === "web" ? 9 : 6,
    borderRadius: 10,
    overflow: "hidden",
    backgroundColor: theme.primary,
    color: "#FFFFFF",
    fontSize: 21,
    lineHeight: 26,
    fontWeight: "700",
  },
  brandName: { color: "#FFFFFF", fontSize: 18, lineHeight: 24, fontWeight: "700" },
  brandMeta: {
    color: theme.navyAccent,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "700",
    letterSpacing: 1.6,
    textTransform: "uppercase",
  },

  /* --------------------------- typography --------------------------- */
  title: { color: theme.text, fontSize: 22, lineHeight: 28, fontWeight: "700", letterSpacing: -0.3 },
  eyebrow: {
    color: theme.faint,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "700",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  muted: { color: theme.muted, fontSize: 13, lineHeight: 19 },
  body: { color: theme.text, fontSize: 15, lineHeight: 23, marginTop: 8 },
  sectionTitle: {
    fontSize: 20,
    lineHeight: 26,
    fontWeight: "700",
    letterSpacing: -0.25,
    color: theme.text,
    marginBottom: 4,
  },
  sectionCaption: { color: theme.muted, fontSize: 13, lineHeight: 19, marginBottom: 14 },
  sectionHeader: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginBottom: 14,
  },
  subheading: {
    color: theme.text,
    fontSize: 15,
    lineHeight: 21,
    fontWeight: "700",
    marginTop: 22,
    marginBottom: 10,
  },
  cardTitle: {
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "700",
    letterSpacing: -0.1,
    color: theme.text,
    textTransform: "capitalize",
  },

  /* ------------------------------ cards ----------------------------- */
  card: { ...raisedSurface, borderRadius: 10, padding: 16, marginBottom: 12 },
  cardHead: {
    borderBottomWidth: 1,
    borderBottomColor: theme.line,
    paddingBottom: 12,
    marginBottom: 12,
  },
  insetPanel: {
    backgroundColor: theme.subtle,
    borderWidth: 1,
    borderColor: theme.line,
    borderRadius: 10,
    padding: 14,
  },

  /* ------------------------------ forms ----------------------------- */
  label: { color: theme.text, fontWeight: "700", marginBottom: 7, fontSize: 13 },
  formTitle: {
    color: theme.text,
    fontSize: 17,
    lineHeight: 23,
    fontWeight: "700",
    letterSpacing: -0.15,
    marginBottom: 12,
  },
  input: {
    backgroundColor: theme.inset,
    borderWidth: 1,
    borderColor: theme.lineInput,
    borderRadius: 8,
    padding: 13,
    marginBottom: 14,
    color: theme.text,
    fontFamily: appFontFamily,
    fontSize: 16,
    lineHeight: 22,
  },
  compactInput: {
    backgroundColor: theme.inset,
    borderWidth: 1,
    borderColor: theme.lineInput,
    borderRadius: 8,
    padding: 12,
    marginBottom: 10,
    color: theme.text,
    fontFamily: appFontFamily,
    fontSize: 16,
    lineHeight: 22,
  },
  multilineInput: { minHeight: 96, textAlignVertical: "top" },

  /* ----------------------------- buttons ---------------------------- */
  primaryButton: {
    backgroundColor: theme.primary,
    minHeight: 48,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 6,
  },
  primaryText: { color: "#FFFFFF", fontWeight: "700" },
  secondaryButton: {
    ...raisedSurface,
    borderColor: theme.lineStrong,
    minHeight: 48,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  secondaryText: { color: theme.text, fontWeight: "700" },
  disabled: { opacity: 0.4 },
  helper: { color: theme.muted, textAlign: "center", marginTop: 14, fontSize: 12, lineHeight: 18 },
  error: { color: theme.danger, marginBottom: 10, fontSize: 13, lineHeight: 19 },
  smallButton: {
    backgroundColor: theme.primary,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 8,
    minHeight: 40,
    justifyContent: "center",
  },
  outlineSmallButton: {
    borderColor: theme.lineStrong,
    borderWidth: 1,
    backgroundColor: theme.inset,
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 8,
    minHeight: 40,
    justifyContent: "center",
  },
  requestActions: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 4 },

  /* ---------------------------- app chrome -------------------------- */
  appBar: {
    backgroundColor: theme.inset,
    borderBottomWidth: 1,
    borderBottomColor: theme.line,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    zIndex: 2,
  },
  header: {
    backgroundColor: theme.inset,
    borderBottomWidth: 1,
    borderBottomColor: theme.line,
    paddingHorizontal: 14,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    zIndex: 2,
  },
  headerIdentity: { flex: 1, minWidth: 0 },
  headerActions: { flexDirection: "row", alignItems: "center", gap: 6 },
  headerButton: {
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 9,
    minHeight: 40,
    justifyContent: "center",
    backgroundColor: theme.subtle,
    borderWidth: 1,
    borderColor: theme.line,
  },
  avatar: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { color: "#FFFFFF", fontSize: 14, fontWeight: "700" },
  roleText: {
    color: theme.muted,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
    textTransform: "capitalize",
    marginTop: 2,
  },
  refresh: { color: theme.primaryDeep, fontSize: 12, fontWeight: "700" },
  logout: { color: theme.danger, fontSize: 12, fontWeight: "700" },
  pageBand: { paddingHorizontal: 16, paddingTop: 16, paddingBottom: 2, maxWidth: 960, width: "100%", alignSelf: "center" },
  content: {
    padding: 16,
    paddingBottom: TAB_BAR_HEIGHT + 28,
    maxWidth: 960,
    width: "100%",
    alignSelf: "center",
  },
  notice: {
    borderRadius: 8,
    backgroundColor: theme.primarySoft,
    padding: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: theme.primaryBorder,
  },
  noticeText: { color: theme.primaryDeep, fontSize: 13, lineHeight: 19 },

  /* ------------------------------ hero ------------------------------ */
  hero: { backgroundColor: theme.navy, borderRadius: 12, padding: 18, marginBottom: 14 },
  heroLabel: {
    color: theme.navyAccent,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  heroValue: {
    color: "#FFFFFF",
    fontSize: 27,
    lineHeight: 33,
    fontWeight: "700",
    letterSpacing: -0.4,
    marginVertical: 6,
  },
  heroMeta: { color: theme.navyText, fontSize: 13, lineHeight: 20 },

  /* ----------------------------- metrics ---------------------------- */
  grid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  metric: {
    ...raisedSurface,
    minWidth: 145,
    flexGrow: 1,
    flexBasis: 145,
    borderRadius: 10,
    padding: 14,
  },
  metricValue: {
    color: theme.text,
    fontSize: 22,
    lineHeight: 28,
    fontWeight: "700",
    letterSpacing: -0.3,
    marginTop: 4,
  },

  /* ------------------------------ rows ------------------------------ */
  row: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 10,
  },
  flexOne: { flex: 1, minWidth: 160 },
  detailRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 8,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: theme.line,
  },
  rowValue: { color: theme.text, fontWeight: "700", flexShrink: 1, textAlign: "right" },
  listRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: theme.line,
  },

  /* ----------------------------- badges ----------------------------- */
  badge: {
    backgroundColor: theme.primarySoft,
    color: theme.primaryDeep,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: theme.primaryBorder,
    paddingHorizontal: 9,
    paddingVertical: 3,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "700",
    textTransform: "capitalize",
    overflow: "hidden",
  },
  badgePositive: { backgroundColor: theme.successSoft, color: theme.success, borderColor: "#BFE3CC" },
  badgeWarning: { backgroundColor: theme.warningSoft, color: theme.warning, borderColor: "#F2DFA8" },
  badgeDanger: { backgroundColor: theme.dangerSoft, color: theme.danger, borderColor: "#F3C6CD" },
  badgeNeutral: { backgroundColor: theme.hover, color: theme.muted, borderColor: theme.line },

  /* --------------------------- approvals ---------------------------- */
  approvalActions: { gap: 6 },
  approveButton: {
    backgroundColor: theme.success,
    borderRadius: 8,
    paddingHorizontal: 11,
    paddingVertical: 8,
    minHeight: 36,
    justifyContent: "center",
  },
  rejectButton: {
    backgroundColor: theme.dangerSoft,
    borderWidth: 1,
    borderColor: "#F3C6CD",
    borderRadius: 8,
    paddingHorizontal: 11,
    paddingVertical: 8,
    minHeight: 36,
    justifyContent: "center",
  },
  rejectText: { color: theme.danger, fontSize: 12, fontWeight: "700" },

  /* ---------------------------- payslips ---------------------------- */
  payslipNet: { backgroundColor: theme.navy, borderRadius: 10, padding: 16, marginTop: 14, marginBottom: 12 },
  payslipNetLabel: {
    color: theme.navyAccent,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "700",
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  payslipNetValue: {
    color: "#FFFFFF",
    fontSize: 26,
    lineHeight: 32,
    fontWeight: "700",
    letterSpacing: -0.35,
    marginTop: 4,
  },
  payslipSummary: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  payslipSummaryItem: {
    flexGrow: 1,
    flexBasis: 140,
    minWidth: 140,
    backgroundColor: theme.subtle,
    borderWidth: 1,
    borderColor: theme.line,
    borderRadius: 8,
    padding: 12,
  },
  summaryValue: { color: theme.text, fontWeight: "700", marginTop: 4, fontSize: 15 },
  payslipDetails: { borderTopWidth: 1, borderTopColor: theme.line, marginTop: 14, paddingTop: 4 },
  detailHeading: { color: theme.text, fontSize: 13, fontWeight: "700", marginTop: 14, marginBottom: 2 },
  payslipActions: { flexDirection: "row", flexWrap: "wrap", gap: 10, marginTop: 14 },
  compactPrimary: {
    flexGrow: 1,
    flexBasis: 140,
    minWidth: 140,
    minHeight: 44,
    backgroundColor: theme.primary,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },
  compactSecondary: {
    flexGrow: 1,
    flexBasis: 140,
    minWidth: 140,
    minHeight: 44,
    borderColor: theme.lineStrong,
    borderWidth: 1,
    backgroundColor: theme.inset,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
  },

  /* ------------------------------ empty ----------------------------- */
  empty: {
    borderStyle: "dashed",
    borderWidth: 1,
    borderColor: theme.lineStrong,
    borderRadius: 10,
    backgroundColor: theme.subtle,
    padding: 26,
    alignItems: "center",
    marginBottom: 8,
  },

  /* -------------------------- segmented ----------------------------- */
  segmented: {
    flexDirection: "row",
    backgroundColor: theme.hover,
    borderRadius: 10,
    padding: 3,
    gap: 3,
    marginBottom: 14,
  },
  segment: { flex: 1, alignItems: "center", justifyContent: "center", minHeight: 38, borderRadius: 8 },
  segmentActive: { backgroundColor: theme.inset, borderWidth: 1, borderColor: theme.line },
  segmentText: { color: theme.muted, fontSize: 13, fontWeight: "700" },
  segmentTextActive: { color: theme.primaryDeep },

  /* --------------------------- calendar ----------------------------- */
  calendarHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  calendarNav: { flexDirection: "row", alignItems: "center", gap: 6 },
  calendarNavButton: {
    minWidth: 40,
    minHeight: 40,
    borderRadius: 8,
    backgroundColor: theme.subtle,
    borderWidth: 1,
    borderColor: theme.line,
    alignItems: "center",
    justifyContent: "center",
  },
  weekRow: { flexDirection: "row" },
  weekday: {
    flex: 1,
    textAlign: "center",
    color: theme.faint,
    fontSize: 10,
    lineHeight: 14,
    fontWeight: "700",
    letterSpacing: 0.6,
    textTransform: "uppercase",
    paddingVertical: 6,
  },
  dayCell: {
    flex: 1,
    aspectRatio: 1,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    margin: 1,
  },
  dayCellOutside: { opacity: 0.35 },
  dayCellSelected: { backgroundColor: theme.primarySoft, borderWidth: 1, borderColor: theme.primary },
  dayNumber: { color: theme.text, fontSize: 13, lineHeight: 18, fontWeight: "600" },
  dayNumberToday: {
    color: "#FFFFFF",
    fontWeight: "700",
    backgroundColor: theme.primary,
    borderRadius: 999,
    width: 24,
    height: 24,
    textAlign: "center",
    paddingTop: Platform.OS === "web" ? 3 : 2,
    overflow: "hidden",
  },
  dotRow: { flexDirection: "row", gap: 2, marginTop: 3, height: 5, alignItems: "center" },
  dot: { width: 5, height: 5, borderRadius: 999 },
  legendRow: { flexDirection: "row", flexWrap: "wrap", gap: 12, marginTop: 12 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 6 },
  legendText: { color: theme.muted, fontSize: 12, lineHeight: 16 },
  eventRow: {
    flexDirection: "row",
    gap: 10,
    paddingVertical: 11,
    borderBottomWidth: 1,
    borderBottomColor: theme.line,
    alignItems: "flex-start",
  },
  eventStripe: { width: 3, alignSelf: "stretch", borderRadius: 999, minHeight: 34 },

  /* --------------------------- bottom tabs -------------------------- */
  tabs: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: theme.inset,
    borderTopWidth: 1,
    borderTopColor: theme.line,
    flexDirection: "row",
    paddingBottom: Platform.OS === "ios" ? 20 : 6,
    paddingTop: 6,
    paddingHorizontal: 4,
  },
  tabContent: { flexGrow: 1, paddingHorizontal: 8, gap: 4 },
  tab: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 6,
    paddingHorizontal: 2,
    borderRadius: 10,
    gap: 3,
    minHeight: 48,
  },
  activeTab: { backgroundColor: theme.primarySoft },
  tabText: { color: theme.faint, fontSize: 10, lineHeight: 13, fontWeight: "700" },
  activeTabText: { color: theme.primaryDeep },
  tabBadge: {
    position: "absolute",
    top: 2,
    right: "22%",
    minWidth: 16,
    height: 16,
    borderRadius: 999,
    backgroundColor: theme.danger,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 3,
  },
  tabBadgeText: { color: "#FFFFFF", fontSize: 9, lineHeight: 12, fontWeight: "700" },

  /* ---------------------------- more sheet -------------------------- */
  sheetBackdrop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(19,26,38,0.45)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: theme.inset,
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 16,
    paddingBottom: Platform.OS === "ios" ? 34 : 20,
    gap: 6,
  },
  sheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 999,
    backgroundColor: theme.lineStrong,
    alignSelf: "center",
    marginBottom: 12,
  },
  sheetItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 13,
    paddingHorizontal: 12,
    borderRadius: 10,
    minHeight: 52,
  },
  sheetItemActive: { backgroundColor: theme.primarySoft },
  sheetItemText: { color: theme.text, fontSize: 15, fontWeight: "600" },
});

export const TAB_BAR = { height: TAB_BAR_HEIGHT };
