const { hashSecret } = require('../utils/passwords');
const { addDays, dateKey, nowIso, startOfDayIso } = require('../utils/records');

function baseLeaveTypes() {
  return [
    { code: 'casual', name: 'Casual Leave', annualAllowance: 12, color: '#6366F1' },
    { code: 'sick', name: 'Sick Leave', annualAllowance: 10, color: '#10B981' },
    { code: 'earned', name: 'Earned Leave', annualAllowance: 18, color: '#F59E0B' },
    { code: 'unpaid', name: 'Unpaid Leave', annualAllowance: 0, color: '#6B7280' },
  ];
}

function makeCompany(overrides) {
  const now = nowIso();
  return {
    _id: overrides._id,
    name: overrides.name,
    code: overrides.code,
    email: overrides.email,
    phone: overrides.phone || '+91 98765 43210',
    domain: overrides.domain || null,
    isVerified: overrides.isVerified ?? true,
    verificationStatus: overrides.isVerified === false ? 'pending' : 'verified',
    status: overrides.status || (overrides.isVerified === false ? 'pending' : 'active'),
    verificationCode: overrides.verificationCode || '000000',
    subscription: {
      plan: 'Professional',
      pricePerUser: 19,
      annualDiscountPercent: 10,
      billingCycle: 'monthly',
      billingMode: 'manual_offline',
      paymentGateway: null,
      status: 'active',
      startedAt: now,
      currentPeriodStart: addDays(new Date(), -20).toISOString(),
      currentPeriodEnd: addDays(new Date(), 10).toISOString(),
      nextRenewalAt: addDays(new Date(), 10).toISOString(),
      graceEndsAt: null,
      pausedAt: null,
      freeAdminSeats: 1,
      paidSeats: 0,
      ...(overrides.subscription || {}),
    },
    branding: {
      primaryColor: '#6366F1',
      secondaryColor: '#8B5CF6',
      logo: null,
      ...(overrides.branding || {}),
    },
    settings: {
      timezone: 'Asia/Kolkata',
      officeStart: '09:30',
      officeEnd: '18:30',
      gpsTracking: true,
      autoCheckIn: true,
      leaveApproval: true,
      desktopMonitoring: true,
      requirePhotoAttendance: false,
      ...(overrides.settings || {}),
    },
    attendanceAreas: overrides.attendanceAreas || [
      {
        _id: `${overrides._id}_area_main`,
        name: 'Main Office',
        address: 'QHR Demo Office',
        latitude: 19.076,
        longitude: 72.8777,
        radiusMeters: 150,
      },
    ],
    leaveTypes: overrides.leaveTypes || baseLeaveTypes(),
    holidays: overrides.holidays || [
      { date: '2026-01-26', name: 'Republic Day' },
      { date: '2026-08-15', name: 'Independence Day' },
      { date: '2026-10-02', name: 'Gandhi Jayanti' },
    ],
    createdAt: now,
    updatedAt: now,
  };
}

function makeEmployee(overrides) {
  const now = nowIso();
  const firstName = overrides.firstName || 'QHR';
  const lastName = overrides.lastName || 'User';
  return {
    _id: overrides._id,
    companyId: overrides.companyId,
    employeeId: overrides.employeeId,
    firstName,
    lastName,
    name: `${firstName} ${lastName}`.trim(),
    email: overrides.email,
    phone: overrides.phone || '+91 90000 00000',
    role: overrides.role || 'employee',
    department: overrides.department || 'Operations',
    designation: overrides.designation || 'Employee',
    managerId: overrides.managerId || null,
    status: 'active',
    dateOfJoining: overrides.dateOfJoining || '2025-04-01',
    passcodeHash: hashSecret(overrides.passcode || '1234'),
    passwordHash: hashSecret(overrides.password || overrides.passcode || '1234'),
    requiresPasswordChange: Boolean(overrides.requiresPasswordChange),
    lastLoginAt: null,
    createdAt: now,
    updatedAt: now,
  };
}

function makeLeaveBalance(employeeId) {
  return {
    employeeId,
    year: 2026,
    balances: {
      casual: { total: 12, used: 0, remaining: 12 },
      sick: { total: 10, used: 0, remaining: 10 },
      earned: { total: 18, used: 0, remaining: 18 },
      unpaid: { total: 0, used: 0, remaining: 0 },
    },
  };
}

function createSeedData() {
  const today = dateKey();
  const yesterday = dateKey(addDays(new Date(), -1));
  const now = nowIso();

  const companies = [
    makeCompany({
      _id: 'company_qhr',
      name: 'QHR Demo',
      code: 'QHR',
      email: 'admin@qhr.com',
      domain: 'qhr.com',
      phone: '+91 99999 11111',
      subscription: {
        billingMode: 'manual_offline',
        freeAdminEmployeeId: 'emp_qhr_company_admin',
        paidSeats: 2,
        customRenewalAmount: 95,
        customTerms: 'Platform-managed offline account; billing does not control access.',
      },
    }),
    makeCompany({
      _id: 'company_testco',
      name: 'Test Company',
      code: 'TESTCO',
      email: 'company@example.com',
      domain: 'testco.example',
      phone: '+91 99999 22222',
      subscription: {
        billingMode: 'automatic',
        paymentGateway: 'cashfree',
        freeAdminEmployeeId: 'emp_company_admin',
        paidSeats: 10,
        pricePerUser: 19,
      },
    }),
  ];

  const employees = [
    makeEmployee({
      _id: 'emp_super_admin',
      companyId: 'company_qhr',
      employeeId: 'SUPER001',
      firstName: 'QHR',
      lastName: 'Admin',
      email: 'admin@qhr.com',
      role: 'super_admin',
      department: 'Platform',
      designation: 'Super Admin',
      password: 'admin123',
    }),
    makeEmployee({
      _id: 'emp_qhr_company_admin',
      companyId: 'company_qhr',
      employeeId: 'COMPANY001',
      firstName: 'Company',
      lastName: 'Admin',
      email: 'company-admin@qhr.com',
      role: 'admin',
      department: 'Operations',
      designation: 'Company Admin',
      passcode: 'password123',
      password: 'password123',
    }),
    makeEmployee({
      _id: 'emp_qhr_001',
      companyId: 'company_qhr',
      employeeId: 'EMP001',
      firstName: 'Rahul',
      lastName: 'Sharma',
      email: 'emp001@example.com',
      role: 'employee',
      department: 'Engineering',
      designation: 'Frontend Developer',
      managerId: 'emp_qhr_company_admin',
      passcode: 'emp123',
      password: 'emp123',
    }),
    makeEmployee({
      _id: 'emp_company_admin',
      companyId: 'company_testco',
      employeeId: 'ADMIN001',
      firstName: 'Company',
      lastName: 'Admin',
      email: 'company@example.com',
      role: 'admin',
      department: 'Management',
      designation: 'Company Admin',
      password: 'password123',
    }),
    makeEmployee({
      _id: 'emp_admin_testco',
      companyId: 'company_testco',
      employeeId: 'ADMIN002',
      firstName: 'Asha',
      lastName: 'Admin',
      email: 'admin@testco.com',
      role: 'admin',
      department: 'Management',
      designation: 'Admin',
      password: 'admin123',
    }),
    makeEmployee({
      _id: 'emp_hr_001',
      companyId: 'company_testco',
      employeeId: 'HR001',
      firstName: 'Hari',
      lastName: 'Rao',
      email: 'hr@testco.com',
      role: 'hr',
      department: 'Human Resources',
      designation: 'HR Manager',
      password: 'password123',
    }),
    makeEmployee({
      _id: 'emp_mgr_001',
      companyId: 'company_testco',
      employeeId: 'MGR001',
      firstName: 'Meera',
      lastName: 'Singh',
      email: 'manager@testco.com',
      role: 'manager',
      department: 'Engineering',
      designation: 'Engineering Manager',
      password: 'password123',
    }),
    makeEmployee({
      _id: 'emp_001',
      companyId: 'company_testco',
      employeeId: 'EMP001',
      firstName: 'John',
      lastName: 'Doe',
      email: 'employee@testco.com',
      role: 'employee',
      department: 'Engineering',
      designation: 'Software Engineer',
      managerId: 'emp_mgr_001',
      password: 'password123',
    }),
  ];

  return {
    meta: {
      seededAt: now,
      schemaVersion: 2,
    },
    companies,
    employees,
    leaveBalances: employees.map((employee) => makeLeaveBalance(employee._id)),
    attendances: [
      {
        _id: 'att_yesterday_emp001',
        companyId: 'company_testco',
        employeeId: 'emp_001',
        date: startOfDayIso(yesterday),
        dateKey: yesterday,
        checkIn: {
          time: `${yesterday}T04:05:00.000Z`,
          method: 'geofence',
          location: { latitude: 19.076, longitude: 72.8777, accuracy: 20 },
        },
        checkOut: {
          time: `${yesterday}T13:02:00.000Z`,
          method: 'manual',
          location: { latitude: 19.076, longitude: 72.8777, accuracy: 25 },
        },
        workDuration: 537,
        status: 'present',
        isLate: false,
        lateByMinutes: 0,
        createdAt: now,
        updatedAt: now,
      },
    ],
    leaves: [
      {
        _id: 'leave_seed_emp001',
        companyId: 'company_testco',
        employeeId: 'emp_001',
        leaveType: 'casual',
        startDate: '2026-07-20',
        endDate: '2026-07-20',
        days: 1,
        reason: 'Seeded personal leave for approval testing',
        status: 'pending',
        createdAt: now,
        updatedAt: now,
      },
    ],
    wfhRequests: [],
    grievances: [],
    desktopActivities: [
      {
        _id: 'desktop_today_emp001',
        companyId: 'company_testco',
        employeeId: 'emp_001',
        dateKey: today,
        sessionStart: null,
        sessionEnd: null,
        snapshots: [],
        topApps: [],
        topCategories: [],
        createdAt: now,
        updatedAt: now,
      },
    ],
    desktopConsents: [],
    desktopStates: [],
    demoRequests: [],
    contactMessages: [],
    payroll: [
      {
        _id: 'payroll_seed_emp001_2026_06',
        companyId: 'company_testco',
        employeeId: 'emp_001',
        period: '2026-06',
        basic: 30000,
        hra: 12000,
        allowances: 3000,
        deductions: 2400,
        gross: 45000,
        net: 42600,
        status: 'approved',
        approvedBy: 'emp_company_admin',
        approvedAt: now,
        createdAt: now,
        updatedAt: now,
      },
    ],
    projects: [],
    tasks: [],
    subscriptionPlans: [
      { _id: 'plan_starter', name: 'Starter', pricePerUser: 19, annualDiscountPercent: 0, freeAdminSeats: 1, status: 'active', userLimit: null },
      { _id: 'plan_professional', name: 'Professional', pricePerUser: 29, annualDiscountPercent: 10, freeAdminSeats: 1, status: 'active', userLimit: null },
      { _id: 'plan_enterprise', name: 'Enterprise', pricePerUser: null, annualDiscountPercent: 0, freeAdminSeats: 1, status: 'active', userLimit: null },
    ],
    billingInvoices: [
      {
        _id: 'invoice_qhr_manual_2026_07',
        invoiceNumber: 'QHR-2026-0001',
        companyId: 'company_qhr',
        kind: 'renewal',
        billingCycle: 'monthly',
        seatCount: 2,
        pricePerSeat: 19,
        issueDate: addDays(new Date(), -12).toISOString(),
        dueDate: addDays(new Date(), -2).toISOString(),
        periodStart: addDays(new Date(), -20).toISOString(),
        periodEnd: addDays(new Date(), 10).toISOString(),
        subtotal: 95,
        tax: 0,
        total: 95,
        amountPaid: 40,
        status: 'partially_paid',
        createdAt: addDays(new Date(), -12).toISOString(),
        updatedAt: now,
      },
      {
        _id: 'invoice_testco_2026_07',
        invoiceNumber: 'QHR-2026-0002',
        companyId: 'company_testco',
        kind: 'renewal',
        billingCycle: 'monthly',
        seatCount: 4,
        pricePerSeat: 19,
        issueDate: addDays(new Date(), -20).toISOString(),
        dueDate: addDays(new Date(), -20).toISOString(),
        periodStart: addDays(new Date(), -20).toISOString(),
        periodEnd: addDays(new Date(), 10).toISOString(),
        subtotal: 76,
        tax: 0,
        total: 76,
        amountPaid: 76,
        status: 'paid',
        createdAt: addDays(new Date(), -20).toISOString(),
        updatedAt: now,
      },
    ],
    billingPayments: [
      {
        _id: 'payment_qhr_part_1', companyId: 'company_qhr', invoiceId: 'invoice_qhr_manual_2026_07', amount: 40,
        method: 'bank_transfer', reference: 'UTR-QHR-0001', proofUrl: null, notes: 'Seeded part payment', status: 'cleared',
        submittedBy: 'emp_qhr_company_admin', submittedByName: 'Company Admin', verifiedBy: 'emp_super_admin', verifiedAt: now,
        createdAt: addDays(new Date(), -5).toISOString(), updatedAt: now,
      },
      {
        _id: 'payment_testco_renewal', companyId: 'company_testco', invoiceId: 'invoice_testco_2026_07', amount: 76,
        method: 'cashfree', reference: 'CF-SEED-0001', proofUrl: null, notes: 'Seeded automatic renewal', status: 'cleared',
        submittedBy: 'emp_company_admin', submittedByName: 'Company Admin', verifiedBy: 'gateway_cashfree', verifiedAt: now,
        createdAt: addDays(new Date(), -20).toISOString(), updatedAt: now,
      },
    ],
    billingNotifications: [],
    paymentGateways: [
      { code: 'cashfree', name: 'Cashfree', enabled: true, isDefault: true, mode: 'test' },
      { code: 'payu', name: 'PayU', enabled: true, isDefault: false, mode: 'test' },
    ],
    sessions: [],
    counters: {
      company: 2,
      employee: 6,
      leave: 1,
      wfh: 0,
      grievance: 0,
      attendance: 1,
      desktop: 1,
    },
  };
}

module.exports = {
  createSeedData,
};
